{
   # General parameters
  "mode": "Sample",
  "run_name": "sample",
  "batch_size": 16,
  "any_time": 1,

  # Sampling parameters
  "ddim_timesteps": 500,
  "plot": true,
  "sampling_mode": "guided",
  "n_sample": 16,
  "random_noise": true,

  # Data parameters
  "data_dir": "/users/celdev/jrabault/POESY/DDPM_gen/data/",
  "csv_file": "IS_method_labels.csv",
  "v_i": 3,
  "var_indexes": ["u", "v", "t2m"],
  "crop": [78,206,55,183],
  "invert_norm": false,
  "image_size": 128,
  "mean_file": "mean_with_orog.npy",
  "max_file": "max_with_orog.npy",
  "guiding_col": "ensemble_id",
  # Model parameters
  "scheduler": true,
  "scheduler_epoch": 10,
  "resume": false,
  "epochs": 10,
  "beta_schedule": "linear",
  "model_path": "/users/celdev/jrabault/POESY/DDPM-weather/run_3/best.pt",

  # Tracking parameters
  "wandbproject": "my_project",
  "use_wandb": false,
  "entityWDB": "my_entity"
}
