{
   # General parameters
  "mode": "Train",
  "run_name": "run_256_guided",
  "batch_size": 4,
  "any_time": 25,

  # Sampling parameters
  "ddim_timesteps": 500,
  "plot": true,
  "sampling_mode": "simple",
  "n_sample": 4,
  "random_noise": true,

  # Data parameters
  "data_dir": "/users/celdev/jrabault/POESY/DDPM_gen/data/",
  "csv_file": "IS_method_labels.csv",
  "v_i": 3,
  "var_indexes": ["u", "v", "t2m"],
  "crop": [0,256,0,256],
  "invert_norm": false,
  "image_size": 256,
  "mean_file": "mean_with_orog.npy",
  "max_file": "max_with_orog.npy",
  "guiding_col": "ensemble_id",

  # Model parameters
  "scheduler": true,
  "scheduler_epoch": 500,
  "resume": false,
  "epochs": 500,
  "beta_schedule": "linear",

  # Tracking parameters
  "wandbproject": "DDPM_re",
  "use_wandb": true,
  "entityWDB": "jrabault"
}
