{
  # General parameters
  "mode": "Train",
  "run_name": "run_train",
  "batch_size": 1,
  "any_time": 25,

  # Sampling parameters
  "ddim_timesteps": 50,
  "plot": true,
  "sampling_mode": "simple",
  "n_sample": 4,
  "random_noise": true,

  # Data parameters
  "data_dir": "$ALL_CCFRWORK/commun/IS_1_1.0_0_0_0_0_0_256_large_lt_done/",
  "csv_file": "Large_lt_train_labels_1_ens.csv",
  "v_i": 3,
  "var_indexes": [ "u", "v", "t2m" ],
  "crop": [0,256,0,256 ],
  "invert_norm": false,
  "image_size": 256,
  "mean_file": "stat_files_Massif_Central/mean_rr.npy",
  "max_file": "stat_files_Massif_Central/std_rr.npy",
  "guiding_col": "ensemble_id",

  # Model parameters
  "scheduler": true,
  "scheduler_epoch": 1,
  "resume": false,
  "epochs": 1,
  "beta_schedule": ["linear", "cosine"],
  "lr": [0.0001, 0.0005],
  "dim": 64,
  "dim_mults": [1, 2, 4, 8],
  
  # Tracking parameters
  "wandbproject": "your_wandb_project",
  "use_wandb": true,
  "entityWDB": "your_entity"
}
